name: Delete S3 Bucket

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: "Name of the S3 bucket to delete"
        required: true

jobs:
  delete-bucket:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Configuration des identifiants AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-1'

      # Étape 2 : Supprimer tous les objets du bucket
      - name: Delete all objects in the bucket
        run: |
          aws s3 rm s3://${{ github.event.inputs.bucket_name }} --recursive

      # Étape 3 : Supprimer le bucket
      - name: Delete the bucket
        run: |
          aws s3 rb s3://${{ github.event.inputs.bucket_name }}
