---
name: Deploy S3 Upload

on:

  workflow_dispatch:
   inputs:
     testing_bucket_name:
      description: create s3 sample bucket
      required: true


jobs:
  createS3_upload_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Create S3 Bucket
        run: |
          aws s3 mb s3://${{ github.event.inputs.testing_bucket_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'

      - name: Upload file
        run: | 
          aws s3 cp Data/Image.jpeg s3://${{ github.event.inputs.testing_bucket_name }}/DeployS3Upload/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'
